import models.DeepLabv3_plus
import models.MAResUNet
import models.HRNet
import models.HRNet_OCR
import models.UNet
import models.UNet_PReLU
import models.UNet_Attention
import models.UNet_SE
import models.UNet_CA
import models.UNet_CCA
import models.UNet_CBAM
import models.UNet_CP
import models.UNet_PReLU_Attention
import models.UNet_ECA_CP
import models.OURS
import models.UNet_PReLU_ECA_bCP
